# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goodlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.IntegerField()),
                ('path1', models.CharField(max_length=256)),
                ('path2', models.CharField(max_length=256)),
                ('collimg', models.CharField(max_length=256)),
                ('goodsimg', models.CharField(max_length=256)),
                ('cityimg', models.CharField(max_length=256)),
                ('send', models.CharField(max_length=256)),
                ('msg', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coll', models.IntegerField()),
                ('productImg', models.CharField(max_length=256)),
            ],
        ),
    ]
